repos:
  - repo: local
    hooks:
      - id: ruff
        name: Ruff Linter
        entry: ruff . --fix
        language: system
        always_run: true
        pass_filenames: false
      - id: ruff-format
        name: Ruff Formatter
        entry: ruff format .
        language: system
        always_run: true
        pass_filenames: false

