data:
  train_data_path: data/train
  training_data: anisotropic
model:
  decoder_layers:
  - 100
  - 100
  - 100
  - 100
  encoder_layers:
  - 100
  - 100
  - 100
  - 100
  name: bitnet_synthetic
run_id: d2438f75-0e28-43cc-b037-cd282a72c158
training:
  batch_size: 64
  epochs: 10
  learning_rate: 0.001
