model:
  name: "bitnet_vae" # "bitnet_vae" or "baseline_vae"

training:
  batch_size: 64
  epochs: 50
  learning_rate: 0.0003

data:
  train_data_path: "data/train"
  training_data: "anisotropic" # "normal" or "anisotropic" or "spiral"

output:
  plot_dir: "./visualize/plots"
